routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\ReportArticleController;
use App\Http\Controllers\ReportMessageController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Laravel\Socialite\Facades\Socialite;
use App\Models\Employee;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->middleware('auth');

Route::resource('/employee',EmployeeController::class);
Route::resource('/user',UserController::class);
Route::resource('/reportMessage',ReportMessageController::class);
Route::resource('/reportArticles',ReportArticleController::class);
Route::resource('/articles',ArticleController::class);
Route::resource('/category',CategoryController::class);

Route::resource('/message',MessageController::class);

Route::get('/report-users',[UserController::class, 'usersReport'])->name('user.repor');

Route::get('/report-user-message/{id}',[ReportMessageController::class, 'showReportByUser'])->name('user.report-message');
Route::get('/report-user-article-{id}',[ReportArticleController::class,'showReportByUser'])->name('user.report-article');


Route::get('/reportMessage/{id}/accepted',[ReportMessageController::class,'acceptedMessage'])->name('reportMessage.accepted');
Route::get('/reportMessage/{id}/rejected',[ReportMessageController::class,'rejectedMessage'])->name('reportMessage.rejected');

Route::get('/reportArticle/{id}/accepted',[ReportArticleController::class,'acceptedArticle'])->name('reportArticle.accepted');
Route::get('/reportArticle/{id}/rejected',[ReportArticleController::class,'rejectedArticle'])->name('reportArticle.rejected');

Route::get('/article-by-user/{id}',[ArticleController::class,'searchByUser'])->name('article.user');


Route::get('/article-search',[ArticleController::class,'searchByParameters'])->name('article.search');
Route::get('/user-search',[UserController::class,'searchByParameters'])->name('user.search');


Route::get('/login', [LoginController::class, 'loginForm'])->name('login');
Route::post('/login', [LoginController::class, 'login']);
Route::get('logout', [LoginController::class, 'logout'])->name('logout');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');


Route::get('/login-google', function () {
    return Socialite::driver('google')->redirect();
});

Route::get('/google-callback', function () {
    $user = Socialite::driver('google')->user();
   // dd($user);
    $userExist = Employee::where('email',$user->email)->first();
    if($userExist){
        Auth::login($userExist);
        return redirect('/');
    } else{
        echo "Vete a tomar por culo de mi pagina " . $user->name ;
        die();
    }
    // $user->token
});
require __DIR__.'/auth.php';

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function articles(){
        return $this->hasMany(Article::class,'owner_id','id');
    }

    public function messageTransmitter(){
        return $this->hasMany(Message::class,'id_transmitter','id');
    }

    public function messageReciver(){
        return $this->hasManyThrough(Message::class,Article::class,'owner_id','id_article');
    }

    public function messageReport(){
        return $this->hasManyThrough(ReportMessage::class,Message::class,'id_transmitter','message_id',);
    }

    public function articleReport(){
        return $this->hasManyThrough(ReportArticle::class,Article::class,'owner_id','article_id',);
    }

    public function articleReportAccepted(){
        return $this->hasManyThrough(ReportArticle::class,Article::class,'owner_id','article_id')->where('accepted',true);
    }

    public function messageReportAccepted(){
        return $this->hasManyThrough(ReportMessage::class,Message::class,'id_transmitter','message_id')->where('accepted',true);
    }

    public function valorations(){
        return $this->hasMany('App\Models\Valoration','id_user_receptor','id');
    }


    public  function scopeName( $query, $name){
        if ($name){
            return $query->where('name','like','%'.$name.'%');
        }
    }

    public  function scopeEmail( $query, $name){
        if ($name){
            return $query->where('email','like','%'.$name.'%');
        }
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\ReportArticle;
use App\Models\ReportMessage;
use App\Models\User;
use Illuminate\Http\Request;
use phpDocumentor\Reflection\Types\Integer;
use function Symfony\Component\String\s;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth',['except'=>[]]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::paginate(10);
        return view('users.userList',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::findOrFail($id);
        $reportArticle = 0;
        $reportMessage= 0;
        foreach ($user->articles as $article){
            $reportArticle += $article->reports->where('accepted',true)->count();
        }
        foreach ($user->messageTransmitter as $message){
            $reportMessage += $message->reports->where('accepted',true)->count();
        }
        $stars = 0;
        if ($user->valorations->count() != 0) {
            foreach ($user->valorations as $valoration) {
                $stars += $valoration->stars;
            }
            $stars = (int) round($stars / $user->valorations->count(),1);
        }
        $starsClear = 5 - $stars;

        return view('users.fitxa',compact('user','reportArticle','reportMessage','stars','starsClear'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->delete();
        return redirect()->route('user.index');
    }

    public function usersReport(){

        $reportsMessage = ReportMessage::with('message')->where('accepted',true)->get();
        $reportsArticle = ReportArticle::with('article')->where('accepted',true)->get();
        $allReports = $reportsMessage->concat($reportsArticle)->groupBy('nameUser');

        return view('report.reportUsers',compact('allReports'));
    }

    public function searchByParameters(Request $request){
        if ($request->tipe == 'email'){
            $users = User::email($request->name)->paginate(10);
        } else{
            $users = User::name($request->name)->paginate(10);
            }
        $users->appends(['name'=>$request->name,'tipe'=>$request->tipe]);
        return view('users.userList',compact('users'));
    }

}

resources/views/users/fitxa.blade.php
@extends('layouts.batoiEmpresa')
@section('content')
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-12 row-cols-md-12 row-cols-xl-12 justify-content-center">
                <div  class="col-sm-12 col-md-12 col-lg-12">
                    <h1>Perfil de usuario</h1>
                    @if($reportMessage + $reportArticle >= 3 )
                        <table @class("table table-bordered table-danger")>
                            @else
                                <table @class("table table-bordered")>
                                    @endif
                                    <tr>
                                        <th rowspan="9">
                                            @if($user->imagen)
                                                <img src="{{$user->imagen}}" width="50%" alt="perfilPhoto" class="rounded border border-primary">
                                            @else
                                                <img src="{{asset('images/no-photo-employee.png')}}" width="200px" alt="perfilPhoto" class="rounded border border-primary">
                                            @endif
                                        </th>
                                    </tr>

                                    <tr>
                                        <th>Nombre</th>
                                        <td colspan="2">{{$user->name}}</td>
                                    </tr>
                                    <tr>
                                        <th>Email</th>
                                        <td colspan="2">{{$user->email}}</td>
                                    </tr>
                                    <tr>
                                        <th>Puntucion</th>
                                        <td colspan="2">
                                        @for($i=1;$i<=$stars; $i++)
                                                <i class="bi bi-star-fill"></i>
                                            @endfor
                                            @for($i=1;$i<=$starsClear; $i++)
                                                <i class="bi bi-star"></i>
                                            @endfor
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>Localizacion </th>
                                        <td colspan="2">
                                        <iframe src="{{$user->location}}" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th > Nº Mensajes </th>
                                        <td colspan="2">{{$user->messageTransmitter->count()}}</td>
                                    </tr>
                                    <tr>
                                        <th rowspan="2"> NºDenuncias <br> <span id="numberReport"> {{$reportMessage + $reportArticle}}</span> </th>
                                        <td >Articulos: {{$reportArticle}}</td>
                                        <td>
                                            <a href="{{route('user.report-article',$user)}}"> <i class="bi bi-eye"></i> </a>

                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Mensajes : {{$reportMessage}}</td>
                                        <td>
                                            <a href="{{route('user.report-message',$user)}}"> <i class="bi bi-eye"></i> </a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th> Nº Productos </th>
                                        <td>{{$user->articles->count()}}</td>
                                        <td>
                                            <a href="{{route('article.user',$user)}}"> <i class="bi bi-eye"></i> </a>
                                        </td>
                                    </tr>
                                    <tr >
                                        <td colspan="4" class="text-center">
                                            <form id="deleteUser" action="{{ route('user.destroy', $user) }}" method="POST" class="d-inline-block">
                                                @method('DELETE')
                                                @csrf
                                                <button  class="bi bi-trash">Borrar</button>
                                            </form>
                                        </td>
                                    </tr>
                                </table>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/users/userList.blade.php
@extends('layouts.batoiEmpresa')
@section('content')
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <form method="get" action="{{route('user.search')}}">
            @csrf
            <div class="form-group">
                <input name="name" type="text" class="form-control " id="name"  placeholder="Buscar por nombre" required >
            </div>
            <div class="form-group">
                Buscar por
                <select name="tipe" id="tipe">
                    <option value="email">Email</option>
                    <option value="name">Nombre</option>
                </select>
            </div>
        </form>
        <div class="row gx-4 gx-lg-5 row-cols-12 row-cols-md-12 row-cols-xl-12 justify-content-center">
            <div class="col-sm-12 col-md-12 col-lg-12">

                @include('users.userTable')

                <div class="d-flex justify-content-center">
                    {!! $users->links() !!}
                </div>

            </div>
        </div>
    </div>
</section>
@endsection

resources/views/users/userTable.blade.php
<h1>Listado de Usuarios</h1>
<table class="table table-striped table-hover">
    <thead class="thead-dark bg-primary">
    <tr>
        <th>Id</th>
        <th>Nombre</th>
        <th>Email</th>
        <th>Foto</th>
        <th>Acciones</th>
    </tr>
    </thead>
    <tbody>
    @foreach($users as $user)
    <tr>
        <td>{{$user->id}}</td>
        <td>{{$user->name}}</td>
        <td>{{$user->email}}</td>
        <td>
            @if($user->imagen)
            <img src="{{asset($user->imagen)}}" width="50px">
            @else
                <img src="{{asset('images/no-photo-employee.png')}}" width="50px">
            @endif
        </td>
        <td>
            <button
                class="btn btn-sm"
                title="Ver Usurio"
            >
                <a href="{{route('user.show',$user)}}"> <i class="bi bi-eye"></i> </a>
            </button>
        </td>
    </tr>
    @endforeach
    </tbody>
</table>