routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\ReportArticleController;
use App\Http\Controllers\ReportMessageController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Laravel\Socialite\Facades\Socialite;
use App\Models\Employee;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->middleware('auth');

Route::resource('/employee',EmployeeController::class);
Route::resource('/user',UserController::class);
Route::resource('/reportMessage',ReportMessageController::class);
Route::resource('/reportArticles',ReportArticleController::class);
Route::resource('/articles',ArticleController::class);
Route::resource('/category',CategoryController::class);

Route::resource('/message',MessageController::class);

Route::get('/report-users',[UserController::class, 'usersReport'])->name('user.repor');

Route::get('/report-user-message/{id}',[ReportMessageController::class, 'showReportByUser'])->name('user.report-message');
Route::get('/report-user-article-{id}',[ReportArticleController::class,'showReportByUser'])->name('user.report-article');


Route::get('/reportMessage/{id}/accepted',[ReportMessageController::class,'acceptedMessage'])->name('reportMessage.accepted');
Route::get('/reportMessage/{id}/rejected',[ReportMessageController::class,'rejectedMessage'])->name('reportMessage.rejected');

Route::get('/reportArticle/{id}/accepted',[ReportArticleController::class,'acceptedArticle'])->name('reportArticle.accepted');
Route::get('/reportArticle/{id}/rejected',[ReportArticleController::class,'rejectedArticle'])->name('reportArticle.rejected');

Route::get('/article-by-user/{id}',[ArticleController::class,'searchByUser'])->name('article.user');


Route::get('/article-search',[ArticleController::class,'searchByParameters'])->name('article.search');
Route::get('/user-search',[UserController::class,'searchByParameters'])->name('user.search');


Route::get('/login', [LoginController::class, 'loginForm'])->name('login');
Route::post('/login', [LoginController::class, 'login']);
Route::get('logout', [LoginController::class, 'logout'])->name('logout');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');


Route::get('/login-google', function () {
    return Socialite::driver('google')->redirect();
});

Route::get('/google-callback', function () {
    $user = Socialite::driver('google')->user();
   // dd($user);
    $userExist = Employee::where('email',$user->email)->first();
    if($userExist){
        Auth::login($userExist);
        return redirect('/');
    } else{
        echo "Vete a tomar por culo de mi pagina " . $user->name ;
        die();
    }
    // $user->token
});
require __DIR__.'/auth.php';

resources/views/report/reportList.blade.php
@extends('layouts.batoiEmpresa')
@section('content')
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-12 row-cols-md-12 row-cols-xl-12 justify-content-center">
                <div class="col-sm-12 col-md-12 col-lg-12">
                    @isset($reportArticle)
                        @include('report.reportTableArticle')
                        <div class="d-flex justify-content-center">
                            {!! $reportArticle->links() !!}
                        </div>
                    @endif
                    @isset($reportMessage)
                        @include('report.reportTableMessage')
                            <div class="d-flex justify-content-center">
                                {!! $reportMessage->links() !!}
                            </div>
                    @endif
                </div>

            </div>
        </div>
    </section>
@endsection

resources/views/report/reportTableArticle.blade.php
<h1>Reporte de Articulos</h1>
<table class="table table-striped table-hover">
    <thead class="thead-dark bg-primary">
    <tr>
        <th>Id</th>
        <th>Propietario</th>
        <th>descripion</th>
        <th>Demandante</th>
        <th>Acciones</th>
    </tr>
    </thead>
    <tbody>
    @foreach($reportArticle as $report)

        @if($report->accepted === null)
            <tr>
        @elseif($report->accepted)
            <tr class="table-danger">
        @else
            <tr class="table-primary">
                @endif
                <td>{{$report->id}}</td>
                <td>{{$report->article->user->name}}</td>
                <td>{{$report->description}}</td>
                <td>{{$report->userReport->name}}</td>

                <td>
                    <a href="{{route('articles.show',$report->article)}}"><i class="bi bi-eye"></i></a>

                    @if( $report->accepted === null ||  $report->accepted   )
                    <a href="{{route('reportArticle.rejected',$report)}}"><i class="bi bi-hand-thumbs-down"></i></a>
                    @else
                        <i class="bi bi-hand-thumbs-down-fill"></i>
                    @endif
                    @if($report->accepted)
                        <i class="bi bi-hand-thumbs-up-fill"></i>
                    @else
                        <a href="{{route('reportArticle.accepted',$report)}}"><i class="bi bi-hand-thumbs-up"></i></a>
                    @endif


                    <form id="deleteUser" action="{{ route('reportMessage.destroy', $report) }}" method="POST" class="d-inline-block">
                        @method('DELETE')
                        @csrf
                        <button  class="bi bi-trash" aria-hidden="true"></button>
                    </form>
                </td>
            </tr>
            @endforeach
    </tbody>
</table>

resources/views/report/reportTableMessage.blade.php
<h1>Reporte de Mensajes</h1>
<table class="table table-striped table-hover">
    <thead class="thead-dark bg-primary">
    <tr>
        <th>Id</th>
        <th>Enviado por</th>
        <th>descripion</th>
        <th>Demandante</th>
        <th>Acciones</th>
    </tr>
    </thead>
    <tbody>
    @foreach($reportMessage as $report)

        @if($report->accepted === null)
            <tr>
        @elseif($report->accepted)
            <tr class="table-danger">
        @else
            <tr class="table-primary">
                @endif
            <td>{{$report->id}}</td>
            <td>{{$report->message->userTransmitter->name}}</td>
            <td>{{$report->description}}</td>
            <td>{{$report->reportUser->name}}</td>

            <td>
                <a href="{{route('message.show',$report->message)}}"><i class="bi bi-eye"></i></a>

                @if( $report->accepted === null ||  $report->accepted   )
                <a href="{{route('reportMessage.rejected',$report)}}"><i class="bi bi-hand-thumbs-down"></i></a>
                    @else
                    <i class="bi bi-hand-thumbs-down-fill"></i>
                @endif
                @if($report->accepted)
                    <i class="bi bi-hand-thumbs-up-fill"></i>
                @else
                    <a href="{{route('reportMessage.accepted',$report)}}"><i class="bi bi-hand-thumbs-up"></i></a>
                @endif

                <form id="deleteUser" action="{{ route('reportMessage.destroy', $report) }}" method="POST" class="d-inline-block">
                    @method('DELETE')
                    @csrf
                    <button  class="bi bi-trash" aria-hidden="true"></button>
                </form>
            </td>
        </tr>
    @endforeach
    </tbody>
</table>

resources/views/report/reportUsers.blade.php
@extends('layouts.batoiEmpresa')
@section('content')
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-12 row-cols-md-12 row-cols-xl-12 justify-content-center">
                <div class="col-sm-12 col-md-12 col-lg-12">
                    <h1>Reporte Usuarios</h1>
                    <table class="table table-striped table-hover">
                        <thead class="thead-dark bg-primary">
                        <tr>
                            <th>Id</th>
                            <th>Nombre</th>
                            <th>Email</th>
                            <th>Foto</th>
                            <th>Denuncias</th>
                            <th>Acciones</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($allReports as $key => $report)
                            @if($report->count() >= 3)
                                <tr class="table-danger">
                                @else
                                <tr>
                                    @endif
                                    <td>{{ $report[0]->message?$report[0]->message->userTransmitter->id:$report[0]->article->user->id}}</td>
                                <td>{{$key}}</td>
                                <td>{{$report[0]->message?$report[0]->message->userTransmitter->email:$report[0]->article->user->email}}</td>
                                <td>
                                    @if($report[0]->message?$report[0]->message->userTransmitter->imagen:'')
                                        <img src="{{$report[0]->message?asset($report[0]->message->userTransmitter->imagen):$report[0]->article->user->imagen}}" width="50px">
                                    @else
                                        <img src="{{asset('images/no-photo-employee.png')}}" width="50px">
                                    @endif
                                </td>
                                <td>{{$report->count()}}</td>
                                <td>
                                    <button
                                        class="btn btn-sm"
                                        title="Ver Usurio"
                                    >
                                       <a href="{{route('user.show',$report[0]->message?$report[0]->message->userTransmitter->id:$report[0]->article->user->id)}}"> <i class="bi bi-eye"></i> </a>
                                    </button>
                                    <button
                                        class="btn btn-sm"
                                        title="Borrar usuario"
                                    >
                                        <i class="bi bi-trash"></i>
                                    </button>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
@endsection