routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\ReportArticleController;
use App\Http\Controllers\ReportMessageController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Laravel\Socialite\Facades\Socialite;
use App\Models\Employee;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->middleware('auth');

Route::resource('/employee',EmployeeController::class);
Route::resource('/user',UserController::class);
Route::resource('/reportMessage',ReportMessageController::class);
Route::resource('/reportArticles',ReportArticleController::class);
Route::resource('/articles',ArticleController::class);
Route::resource('/category',CategoryController::class);

Route::resource('/message',MessageController::class);

Route::get('/report-users',[UserController::class, 'usersReport'])->name('user.repor');

Route::get('/report-user-message/{id}',[ReportMessageController::class, 'showReportByUser'])->name('user.report-message');
Route::get('/report-user-article-{id}',[ReportArticleController::class,'showReportByUser'])->name('user.report-article');


Route::get('/reportMessage/{id}/accepted',[ReportMessageController::class,'acceptedMessage'])->name('reportMessage.accepted');
Route::get('/reportMessage/{id}/rejected',[ReportMessageController::class,'rejectedMessage'])->name('reportMessage.rejected');

Route::get('/reportArticle/{id}/accepted',[ReportArticleController::class,'acceptedArticle'])->name('reportArticle.accepted');
Route::get('/reportArticle/{id}/rejected',[ReportArticleController::class,'rejectedArticle'])->name('reportArticle.rejected');

Route::get('/article-by-user/{id}',[ArticleController::class,'searchByUser'])->name('article.user');


Route::get('/article-search',[ArticleController::class,'searchByParameters'])->name('article.search');
Route::get('/user-search',[UserController::class,'searchByParameters'])->name('user.search');


Route::get('/login', [LoginController::class, 'loginForm'])->name('login');
Route::post('/login', [LoginController::class, 'login']);
Route::get('logout', [LoginController::class, 'logout'])->name('logout');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');


Route::get('/login-google', function () {
    return Socialite::driver('google')->redirect();
});

Route::get('/google-callback', function () {
    $user = Socialite::driver('google')->user();
   // dd($user);
    $userExist = Employee::where('email',$user->email)->first();
    if($userExist){
        Auth::login($userExist);
        return redirect('/');
    } else{
        echo "Vete a tomar por culo de mi pagina " . $user->name ;
        die();
    }
    // $user->token
});
require __DIR__.'/auth.php';

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    public function article(){
        return $this->hasMany(Article::class,'category_id','id');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CategoryUpdateValidator;
use App\Http\Requests\CategoryValidator;
use App\Models\Article;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth',['except'=>[]]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::paginate(10);

        return view('category.list',compact('categories'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('category.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryValidator $request)
    {

        $category = new Category();
        $category->name= $request->get('name');
        $category->desc = $request->get('description');
        $originalName = explode($request->file('photo')->getClientOriginalExtension(),$request->file('photo')->getClientOriginalName())[0];
        $nameFile = generar_token_seguro(5) . $originalName  .  $request->file('photo')->getClientOriginalExtension();
        $category->image = $request->file('photo')->move('images',$nameFile );
        $category->save();
        return redirect(route('category.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);
        return view('category.form',compact('category'));


    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryUpdateValidator $request, $id)
    {
        $category = Category::findOrFail($id);
        $category->name= $request->get('name');
        $category->desc = $request->get('description');

        if ($request->file('photo')){
            $nameFile = str_replace('images/', '', $category->image);
            $category->image = $request->file('photo')->move('images', $nameFile);
        }
        $category->save();
        return redirect(route('category.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::findOrFail($id);
        if ($category->article->count()){
            abort(403,'no puedes borrar esta categoria');
        }
        $category->delete();
        return redirect(route('category.index'));
    }
}

resources/views/category/form.blade.php
@extends('layouts.batoiEmpresa')
@section('content')
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            @if(isset($category))
                <form method="POST" novalidate action="{{route('category.update',$category->id)}}" enctype="multipart/form-data">
                    <h2>Editando</h2>
                    @method('PUT')
                    @else
                        <form method="POST" novalidate action="{{route('category.store')}}" enctype="multipart/form-data">
                            @endif
                            @csrf
                            <?php if (isset($category->id)): ?>
                            <div class="form-group">
                                <label for="name">Editando la categoria:<?= $category->name ?></label>
                                <input name="id" type="hidden" value="<?= $category->id ?>">
                            </div>
                            <?php endif; ?>
                            <div class="form-group">
                                <label for="title">Title:</label>
                                <input name="name" type="text" class="form-control " id="title" aria-describedby="titleHelp" placeholder="Enter Title" value="{{old('name')??(isset($category)?$category->name:'')}}">
                                <small id="nameHelp" class="form-text text-muted">Nombre del  la categoria</small>
                                @if ($errors->has('name'))
                                    <div class="text-danger">
                                        {{ $errors->first('name') }}
                                    </div>
                                @endif

                            </div>
                            <div class="form-group">
                                <label for="description">Description:</label><br>
                                <textarea name="description" > {{old('description')??(isset($category)?$category->desc:'')}}</textarea>
                                <small id="nameHelp" class="form-text text-muted">descripcion de la categoria</small>
                                @if ($errors->has('description'))
                                    <div class="text-danger">
                                        {{ $errors->first('description') }}
                                    </div>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="PhotoFile">Foto categoria</label>
                                <input type="file" name="photo" class="form-control-file " id="PhotoFile" value="{{old('photo')??(isset($category)?asset($category->image):'')}}">
                                @if ($errors->has('photo'))
                                    <div class="text-danger">
                                        {{ $errors->first('photo') }}
                                    </div>
                                @endif
                            </div>
                            <input type="hidden" name="MAX_FILE_SIZE" value="1000000">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
        </div>
    </section>
@endsection

resources/views/category/list.blade.php
@extends('layouts.batoiEmpresa')
@section('content')
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class=" text-center row gx-4 gx-lg-5 row-cols-12 row-cols-md-12 row-cols-xl-12 justify-content-center">
                <div class="col-sm-12 col-md-12 col-lg-12 ">
                    @include('category.table')
                </div>
                <a href="{{route('category.create')}}">
                <button type="button" class="btn btn-success">Añadir nueva</button>
                </a>
            </div>
            <div class="d-flex justify-content-center">
                {!! $categories->links() !!}
            </div>
        </div>
    </section>
@endsection

resources/views/category/table.blade.php
<h1>Listado de Articulos </h1>
<table class="table table-striped table-hover">
    <thead class="thead-dark bg-primary">
    <tr>
        <th>Id</th>
        <th>Nombre</th>
        <th>Email</th>
        <th>Foto</th>
        <th>Articulos</th>
        <th>Acciones</th>
    </tr>
    </thead>
    <tbody>
    @foreach($categories as $categoria)
        <tr>
            <td>{{$categoria->id}}</td>
            <td>{{$categoria->name}}</td>
            <td>{{$categoria->desc}}</td>
            <td>
                @if($categoria->image)
                    <img src="{{asset($categoria->image)}}" width="50px">
                @else
                    <img src="{{asset('images/no-photo-employee.png')}}" width="50px">
                @endif
            </td>
            <td>{{$categoria->article->count()}}</td>

            <td>
                <form id="deleteUser" action="{{ route('category.destroy', $categoria->id) }}" method="POST" class="d-inline-block">
                    @method('DELETE')
                    @csrf
                    <button  ><i class="bi bi-trash"></i></button>
                </form>
                <button
                    class="btn btn-sm"
                    title="Editar categoria"
                >
                    <a href="{{route('category.edit',$categoria)}}">
                    <i class="bi bi-pencil"></i>
                    </a>
                </button>
            </td>
        </tr>
    @endforeach
    </tbody>
</table>