routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\ReportArticleController;
use App\Http\Controllers\ReportMessageController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Laravel\Socialite\Facades\Socialite;
use App\Models\Employee;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->middleware('auth');

Route::resource('/employee',EmployeeController::class);
Route::resource('/user',UserController::class);
Route::resource('/reportMessage',ReportMessageController::class);
Route::resource('/reportArticles',ReportArticleController::class);
Route::resource('/articles',ArticleController::class);
Route::resource('/category',CategoryController::class);

Route::resource('/message',MessageController::class);

Route::get('/report-users',[UserController::class, 'usersReport'])->name('user.repor');

Route::get('/report-user-message/{id}',[ReportMessageController::class, 'showReportByUser'])->name('user.report-message');
Route::get('/report-user-article-{id}',[ReportArticleController::class,'showReportByUser'])->name('user.report-article');


Route::get('/reportMessage/{id}/accepted',[ReportMessageController::class,'acceptedMessage'])->name('reportMessage.accepted');
Route::get('/reportMessage/{id}/rejected',[ReportMessageController::class,'rejectedMessage'])->name('reportMessage.rejected');

Route::get('/reportArticle/{id}/accepted',[ReportArticleController::class,'acceptedArticle'])->name('reportArticle.accepted');
Route::get('/reportArticle/{id}/rejected',[ReportArticleController::class,'rejectedArticle'])->name('reportArticle.rejected');

Route::get('/article-by-user/{id}',[ArticleController::class,'searchByUser'])->name('article.user');


Route::get('/article-search',[ArticleController::class,'searchByParameters'])->name('article.search');
Route::get('/user-search',[UserController::class,'searchByParameters'])->name('user.search');


Route::get('/login', [LoginController::class, 'loginForm'])->name('login');
Route::post('/login', [LoginController::class, 'login']);
Route::get('logout', [LoginController::class, 'logout'])->name('logout');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');


Route::get('/login-google', function () {
    return Socialite::driver('google')->redirect();
});

Route::get('/google-callback', function () {
    $user = Socialite::driver('google')->user();
   // dd($user);
    $userExist = Employee::where('email',$user->email)->first();
    if($userExist){
        Auth::login($userExist);
        return redirect('/');
    } else{
        echo "Vete a tomar por culo de mi pagina " . $user->name ;
        die();
    }
    // $user->token
});
require __DIR__.'/auth.php';

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class Employee extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\EmployeeValidator;
use App\Models\Employee;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth',['except'=>[]]);
        $this->middleware('employee:Employee',['except'=>['index']]);
    }

    public function index()
    {
        $employees = Employee::all();
        return view('employee.employeeList',compact('employees'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $employee = Employee::findOrFail($id);
        return view('employee.form',compact('employee'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(EmployeeValidator $request, $id)
    {
        $employee = Employee::findOrFail($id);
        $employee->name = $request->name;
        $employee->email = $request->email;
        if ($request->file('photo')){
            $originalName = explode($request->file('photo')->getClientOriginalExtension(), $request->file('photo')->getClientOriginalName())[0];
        $nameFile = generar_token_seguro(5) . $originalName . $request->file('photo')->getClientOriginalExtension();
        $employee->imagen = $request->file('photo')->move('images', $nameFile);
    }
        $employee->save();
        return redirect()->route('employee.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

    }
}

resources/views/employee/employeeList.blade.php
@extends('layouts.batoiEmpresa')
@section('content')
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-12 row-cols-md-12 row-cols-xl-12 justify-content-center">
            <div class="col-sm-12 col-md-12 col-lg-12">

                @include('employee.employeeTable')
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/employee/employeeTable.blade.php
<h1>Listado de Empleado</h1>
<table class="table table-striped table-hover">
    <thead class="thead-dark bg-primary">
    <tr>
        <th>Id</th>
        <th>Nombre</th>
        <th>Email</th>
        <th>Foto</th>
        <th>Acciones</th>
    </tr>
    </thead>
    <tbody>
    @foreach($employees as $employe)
        @if(Auth::user()->email == $employe->email)
            <tr class="bg-success">
        @else
            <tr>
        @endif
        <td>{{$employe->id}}</td>
        <td>{{$employe->name}}</td>
        <td>{{$employe->email}}</td>
        <td>
            @if($employe->imagen)
            <img src="{{asset($employe->imagen)}}" width="50px"  @class('rounded-circle')>
            @else
                <img src="{{asset('images/no-photo-employee.png')}}" width="50px">
            @endif
        </td>
        <td>
            @if(Auth::user()->email == $employe->email)

                <button
                    class="btn btn-sm"
                    title="Editar Usuario"
                >
                    <a href="{{route('employee.edit',$employe)}}">
                        <i class="bi bi-pencil"></i>
                    </a>
                </button>
            @endif

        </td>
    </tr>
    @endforeach
    </tbody>
</table>

resources/views/employee/form.blade.php
@extends('layouts.batoiEmpresa')
@section('content')
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            @if(isset($employee))
                <form method="POST" novalidate action="{{route('employee.update',$employee->id)}}" enctype="multipart/form-data">
                    <h2>Editando</h2>
                    @method('PUT')
                    @else
                        <form method="POST" novalidate action="{{route('employee.store')}}" enctype="multipart/form-data">
                            @endif
                            @csrf
                            <?php if (isset($employe->id)): ?>
                            <div class="form-group">
                                <label for="name">Editando la informacion de usuario:<?= $employee->name ?></label>
                            </div>
                            <?php endif; ?>
                            <div class="form-group">
                                <label for="title">Nombre de usuario:</label>
                                <input name="name" type="text" class="form-control " id="title" aria-describedby="titleHelp" placeholder="nombre usuario" value="{{old('name')??(isset($employee)?$employee->name:'')}}">
                                @if ($errors->has('name'))
                                    <div class="text-danger">
                                        {{ $errors->first('name') }}
                                    </div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="title">Email:</label>
                                <input name="email" type="text" class="form-control " id="title" aria-describedby="titleHelp" placeholder="email" value="{{old('email')??(isset($employee)?$employee->email:'')}}">
                                @if ($errors->has('email'))
                                    <div class="text-danger">
                                        {{ $errors->first('email') }}
                                    </div>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="PhotoFile">Foto de Usuario</label>
                                <input type="file" name="photo" class="form-control-file " id="PhotoFile" value="{{old('photo')??(isset($employee)?asset($employee->image):'')}}">
                                @if(isset($employee))
                                Foto Actual:<img src="{{asset($employee->imagen)}}" width="100px"  @class('rounded-circle') alt="sin foto">
                                @endif
                            @if ($errors->has('photo'))
                                    <div class="text-danger">
                                        {{ $errors->first('photo') }}
                                    </div>
                                @endif
                            </div>
                            <input type="hidden" name="MAX_FILE_SIZE" value="1000000">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
        </div>
    </section>
@endsection